
#: import hex kivy.utils.get_color_from_hex
#: set bleu "#46ADF8"
#: set blanc "#f1f1f1"
#: set small dp(12)
#: set medium dp(24)
#: set extra dp(36)
#: set acme "fonts/Acme.ttf"
#: set amble_regular "fonts/amble/Regular.ttf"
#: set amble_italic "fonts/amble/Italic.ttf"
#: set radius_ dp(20)

#: import home_interface home_interface
#: import loginpage loginpage
#: import signup signup

HomeInterface:

